---

name: hello-plutarch
version: 0.0.1

dependencies:
  - base
  - bytestring
  - data-default
  - either
  - text
  - plutus-tx
  - plutus-core
  - plutus-ledger-api
  - plutarch
  - plutarch-extra

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: exe
  dependencies: hello-plutarch
