---

name: haskell.nix

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:

  build-with-cabal:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3.1.0
      - name: Install Nix
        uses: cachix/install-nix-action@v17
      - name: Install Dependencies
        run: nix develop --command true
      - name: Build With Cabal
        run: nix develop --command cabal build
      - name: Run With Cabal
        run: nix develop --command cabal run

  build-with-nix:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3.1.0
      - name: Install Nix
        uses: cachix/install-nix-action@v17
      - name: Install Dependencies
        run: nix develop --command true
      - name: Build With Nix
        run: nix build
      - name: Run With Nix
        run: nix run
