---

name: hpack-sync

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:

  check:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3.1.0

      - name: Install hpack
        run: |
          sudo apt install -yq hpack
          ## The following lines are here to make `libffi.so.6` available on the
          ## system. `libffi` has an extremely stable interface, and therefore
          ## it is not harmful to simply link it to later versions.
          printf 'Manually setting up `libffi.so.6`...\n'
          libffi=$(find /usr/lib -name libffi.so)
          sudo ln -s "$libffi" "$libffi".6

      - name: DEBUG
        run: hpack --version

      - name: Run hpack
        run: hpack

      - name: Check Differences
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            printf 'Error: Running `hpack` creates differences:\n%s\n' "$status"
            exit 7
          fi
