---

name: hpack-sync

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:

  check:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3.1.0

      - name: Install hpack
        run: sudo apt install -yq hpack

      - name: Run hpack
        run: hpack

      - name: Check Differences
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            printf 'Error: Running `hpack` creates differences:\n%s\n' "$status"
            exit 7
          fi
