---

name: template

on:
  push:
    branches:
      - main
  pull_request:
  ## ^^^ FIXME: remove later

jobs:

  sync-template:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          ## A `fetch-depth` of `0` indicates all history for all branches and
          ## tags. This is a fairly brutal way to make sure that we also obtain
          ## the `template` branch.

      - name: Create Temporary Directory
        run: |
          echo 'tmp=${{ runner.temp }}/template' >> $GITHUB_ENV
          mkdir ${{ runner.temp }}/template

      - name: Prepare Template
        run: |
          ## Find everything in the current directory at depth exactly 1. If
          ## they are called `.git` or `.github`, stop exploring them right
          ## away. Otherwise, copy them to `$tmp/`.
          find .                                                      \
            -mindepth 1 -maxdepth 1                                   \
            '('                                                       \
                '(' -name .git -o -name .github ')' -prune            \
                -o -exec cp -R '{}' $tmp/ ';'                         \
            ')'

      - name: [TEST] Create a stupid commit message
        run: |
          echo "COMMIT_MESSAGE=\"C'est un commit message !\"" >> $GITHUB_ENV

      - name: Publish to Branch `template`
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout template
          rm -Rf ./template
          cp -R $tmp ./template
          git add ./template
          git commit --message='Follow ${{ github.sha }}: ${{ env.COMMIT_MESSAGE }}'
          git push origin template
